### ISSUE TITLE
Validating the disk space:

### ISSUE THREAD

**Issue by Anilkumar18** [SociOS-Linux/socios#9]
Validating the disk selected disk space and adding a checklist script for if there is enough space available on the particular disk.

What is the complexity of this. What is hours estimate? How is it tracking? @Anilkumar18 

Complexity : 1
Estimated time: 2-4 hours
Tracking:  We will update the GitHub task card and create a branch called socios#9.so that you can track the work done for a card to a specific branch / pull request / merge.
@mdheller

**Comment by mdheller** [comment]
Let's try to make this easier than it is now. When I went through this I had to guess about what I should be entering. 

If we are subtracting one from another we should provide an estimate for the user. Please provide check list here so I can review. It would be good to get this aligned so that it's more natural and doesn't take several iterations for our users it would be ideal..... This might not be a priority for now, but I wanted to document it and we can re-align the priority once you share the details

**Comment by mdheller** [comment]
I will test this later this week. @Anilkumar18 acknowledged that this has been updated, but want to review the workflow personally. closing for now but will reopen with new comments and reprioritize .
